// <auto-generated />
using System;
using KeoghsKata.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeoghsKata.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220320100642_InsertPromotionalData")]
    partial class InsertPromotionalData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("KeoghsKata.Models.PromotionStoreKeepingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromotionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreKeepingUnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreKeepingUnitId");

                    b.ToTable("PromotionStoreKeepingUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUTC = new DateTime(2022, 3, 20, 10, 6, 41, 895, DateTimeKind.Utc).AddTicks(1188),
                            PromotionType = 1,
                            StoreKeepingUnitId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedUTC = new DateTime(2022, 3, 20, 10, 6, 41, 895, DateTimeKind.Utc).AddTicks(1189),
                            PromotionType = 2,
                            StoreKeepingUnitId = 4
                        });
                });

            modelBuilder.Entity("KeoghsKata.Models.StoreKeepingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoreKeepingUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUTC = new DateTime(2022, 3, 20, 10, 6, 41, 895, DateTimeKind.Utc).AddTicks(1112),
                            ProductName = "A",
                            UnitPrice = 10m
                        },
                        new
                        {
                            Id = 2,
                            CreatedUTC = new DateTime(2022, 3, 20, 10, 6, 41, 895, DateTimeKind.Utc).AddTicks(1114),
                            ProductName = "B",
                            UnitPrice = 15m
                        },
                        new
                        {
                            Id = 3,
                            CreatedUTC = new DateTime(2022, 3, 20, 10, 6, 41, 895, DateTimeKind.Utc).AddTicks(1115),
                            ProductName = "C",
                            UnitPrice = 40m
                        },
                        new
                        {
                            Id = 4,
                            CreatedUTC = new DateTime(2022, 3, 20, 10, 6, 41, 895, DateTimeKind.Utc).AddTicks(1115),
                            ProductName = "D",
                            UnitPrice = 55m
                        });
                });

            modelBuilder.Entity("KeoghsKata.Models.PromotionStoreKeepingUnit", b =>
                {
                    b.HasOne("KeoghsKata.Models.StoreKeepingUnit", "StoreKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StoreKeepingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreKeepingUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
