// <auto-generated />
using System;
using KeoghsKata.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeoghsKata.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220320054247_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("KeoghsKata.Database.DatabaseContext+PromotionStoreKeepingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromotionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreKeepingUnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreKeepingUnitId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("KeoghsKata.Database.DatabaseContext+StoreKeepingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoreKeepingUnits");
                });

            modelBuilder.Entity("KeoghsKata.Database.DatabaseContext+PromotionStoreKeepingUnit", b =>
                {
                    b.HasOne("KeoghsKata.Database.DatabaseContext+StoreKeepingUnit", "StoreKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StoreKeepingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreKeepingUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
