// <auto-generated />
using System;
using KeoghsKata.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeoghsKata.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("KeoghsKata.Database.DatabaseContext+PromotionStoreKeepingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromotionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreKeepingUnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreKeepingUnitId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("KeoghsKata.Database.DatabaseContext+StoreKeepingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoreKeepingUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUTC = new DateTime(2022, 3, 20, 7, 36, 58, 144, DateTimeKind.Utc).AddTicks(4851),
                            ProductName = "A",
                            UnitPrice = 10m
                        },
                        new
                        {
                            Id = 2,
                            CreatedUTC = new DateTime(2022, 3, 20, 7, 36, 58, 144, DateTimeKind.Utc).AddTicks(4853),
                            ProductName = "B",
                            UnitPrice = 15m
                        },
                        new
                        {
                            Id = 3,
                            CreatedUTC = new DateTime(2022, 3, 20, 7, 36, 58, 144, DateTimeKind.Utc).AddTicks(4854),
                            ProductName = "C",
                            UnitPrice = 40m
                        },
                        new
                        {
                            Id = 4,
                            CreatedUTC = new DateTime(2022, 3, 20, 7, 36, 58, 144, DateTimeKind.Utc).AddTicks(4855),
                            ProductName = "D",
                            UnitPrice = 55m
                        });
                });

            modelBuilder.Entity("KeoghsKata.Database.DatabaseContext+PromotionStoreKeepingUnit", b =>
                {
                    b.HasOne("KeoghsKata.Database.DatabaseContext+StoreKeepingUnit", "StoreKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StoreKeepingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreKeepingUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
